### ISSUE TITLE
Beets Audible failing everytime after not being able to get the chapters

### ISSUE THREAD

**Issue by JaegerMaster** [Neurrone/beets-audible#54] opened 2023-07-30 07:35 UTC
Lately, the program fails to match and tag books after the chapter endpint gives a 404 error. It leave the tagging mid-point and does not match the book.

Error:

Error while requesting https://api.audnex.us/books/B0BLJ78Y1Y/chapters: status code 404, Not Found

this happens for monstly newly released books and not for all books.

Beets Audible version: 
beets version 1.6.0
Python version 3.10.6
plugins: audible, copyartifacts, edit, fromfilename, scrub

**Comment by Neurrone** [comment] 2023-07-30 15:19
Yeah this is a known issue. I suspect that the service that Beets-audible uses hasn't gotten info on the chapters yet for new releases.

Does it work for you if you try it 12 - 24 hours later?

**Comment by JaegerMaster** [comment] 2023-07-30 15:54
Nah. I have been seeing this for the last 1 week atleast. i think somehow audible is blocking audnexus from getting the chapter data.

In that case, can we change the script to not fail and tag the book atleast without chapter data?
It can use the existing chapter titles and change anything?

**Comment by Neurrone** [comment] 2023-07-30 16:04
There is no existing chapter titles to fall back on, since the Audnex API is the source of data.

We'll have to wait for updates in the issue you created, laxamentumtech/audnexus#658

**Comment by JaegerMaster** [comment] 2023-07-30 16:09
No worries. Thanks.

Lets wait and see.

**Comment by djdembeck** [comment] 2023-07-30 21:36
Audible requires authentication again for chapters. I've re-added auth to the Audnexus project. This should be merged into production shortly.

**Comment by JaegerMaster** [comment] 2023-08-05 18:21
Thanks. Works properly now.

**Comment by JaegerMaster** [comment] 2023-09-23 05:56
I think this has cropped up again.

**Comment by TaroAM** [comment] 2023-09-23 16:05
I can confirm. Wonder if the error can be handled instead of crashing.

**Comment by Neurrone** [comment] 2024-11-03 13:45
Closing this to do some cleanup of old issues. Let me know if this is still relevant.

**Closed by Neurrone** 2024-11-03 13:45 UTC
